version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Cleaning up old dependencies..."
      - rm -rf $CODEBUILD_SRC_DIR/backend/node_modules
      - echo "Installing dependencies..."
      - npm install --prefix $CODEBUILD_SRC_DIR/backend
      - echo "Checking for vulnerabilities..."
      - npm audit --prefix $CODEBUILD_SRC_DIR/backend || true

  build:
    commands:
      - echo "Installing TypeScript..."
      - npm install -g typescript
      - echo "Building the node server..."
      - npm run build --prefix $CODEBUILD_SRC_DIR/backend

  post_build:
    commands:
      - echo "Syncing build artifacts to S3..."
      - if [ -d "$CODEBUILD_SRC_DIR/backend/build" ]; then
          aws s3 sync $CODEBUILD_SRC_DIR/backend/build/ s3://ask-pdf-http-s3 --delete;
        else
          echo "Build directory does not exist. Skipping S3 sync.";
          exit 1;
        fi
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E6KL8H3RZT697 --paths "/*"

artifacts:
  files:
    - '**/*'
